/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/city-buildings.glb --types --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['industry-factory-hall']: THREE.Mesh
    ['building-train-station']: THREE.Mesh
    ['building-mall']: THREE.Mesh
    ['building-hotel']: THREE.Mesh
    ['building-hospital']: THREE.Mesh
    ['building-cinema']: THREE.Mesh
    ['building-casino']: THREE.Mesh
    ['building-carwash']: THREE.Mesh
    ['industry-warehouse']: THREE.Mesh
  }
  materials: {
    ['LOWPOLY-COLORS']: THREE.MeshStandardMaterial
    ['LOWPOLY-COLORS']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/city-buildings.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['industry-factory-hall'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, -124.117]} userData={{ name: 'industry-factory-hall' }} />
      <mesh geometry={nodes['building-train-station'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, -27.595]} userData={{ name: 'building-train-station' }} />
      <mesh geometry={nodes['building-mall'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, 155.366]} userData={{ name: 'building-mall' }} />
      <mesh geometry={nodes['building-hotel'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, 23.295]} userData={{ name: 'building-hotel' }} />
      <mesh geometry={nodes['building-hospital'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, 65.885]} userData={{ name: 'building-hospital' }} />
      <mesh geometry={nodes['building-cinema'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, 186.612]} userData={{ name: 'building-cinema' }} />
      <mesh geometry={nodes['building-casino'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, -79.585]} userData={{ name: 'building-casino' }} />
      <mesh geometry={nodes['building-carwash'].geometry} material={materials['LOWPOLY-COLORS']} position={[0, 0, 111.177]} userData={{ name: 'building-carwash' }} />
      <mesh geometry={nodes['industry-warehouse'].geometry} material={materials['LOWPOLY-COLORS']} position={[0.204, 0.018, 223.864]} userData={{ name: 'industry-warehouse' }} />
    </group>
  )
}

useGLTF.preload('/city-buildings.glb')
