/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshGLTFModel } from '@/experience/types/modelTypes';
import { createSharedAtlasMaterial } from '@/experience/utils/materialUtils';
import { useGLTF } from '@react-three/drei';
import { ThreeElements } from '@react-three/fiber';

export function FestivalBuildings(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/festival-buildings.glb'
  ) as unknown as MeshGLTFModel;
  const LowpolyMaterial = createSharedAtlasMaterial(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['ferris-wheel001'].geometry}
        material={LowpolyMaterial}
        position={[-322.371, 0, 56.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tent-circus-big001'].geometry}
        material={LowpolyMaterial}
        position={[-306.258, -0.005, 88.341]}
      />
      <group position={[-158.828, 4.975, 43.436]} rotation={[0, Math.PI / 4, 0]} scale={7.75}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stage001_1.geometry}
          material={LowpolyMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stage001_2.geometry}
          material={LowpolyMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stage001_3.geometry}
          material={LowpolyMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/festival-buildings.glb');
