/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshGLTFModel } from '@/experience/types/modelTypes';
import { useGLTF } from '@react-three/drei';
import { ThreeElements } from '@react-three/fiber';

export function TempFloor(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/temp-world-floor-muted.glb'
  ) as unknown as MeshGLTFModel;
  return (
    <group {...props} dispose={null}>
      <group position={[-90, 2.665, -75]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['temp-world-floor002_1'].geometry}
          material={materials['atlas-muted']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['temp-world-floor002_2'].geometry}
          material={materials['muted-curb.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/temp-world-floor-muted.glb');
