/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshGLTFModel } from '@/experience/types/modelTypes';
import { createSharedAtlasMaterial } from '@/experience/utils/materialUtils';
import { useGLTF } from '@react-three/drei';
import { ThreeElements } from '@react-three/fiber';

export function Ground(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/landing/landing-scene-ground.glb'
  ) as unknown as MeshGLTFModel;
  const LowpolyMaterial = createSharedAtlasMaterial(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="land-back"
        castShadow
        receiveShadow
        geometry={nodes['land-back'].geometry}
        material={LowpolyMaterial}
        position={[0, 0.693, -295.132]}
        scale={[289.249, 256.168, 44.943]}
      />
      <mesh
        name="landing-grass"
        castShadow
        receiveShadow
        geometry={nodes['landing-grass'].geometry}
        material={LowpolyMaterial}
        position={[-65.126, 2.71, -147.794]}
      />
    </group>
  );
}

useGLTF.preload('/models/landing/landing-scene-ground.glb');
